version: '3.1'
services:
  db:
    container_name: mysql-8-db
    image: mysql:8
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123root123
    ports:
      - 3306:3306
